<section class="w-100 mt-5 mb-5">
    <div class="container">
        <div class="row">
            <div class="col-md-10">
                <div class="disTitle">
                    <h1 class="aboutTitle">Know Your RERA</h1>
                </div>
                <div class="disTitleInfo">
                    <h2 class="know-head">Real Estate (Regulations and Development) Act, 2016</h2>
                    <p><strong>&nbsp;</strong><strong>Prologue</strong></p>
                    <p>The need for regulations and uniform guidelines was being felt by the industry which perceived negatively by consumers because of unscrupulous activities of few. A long standing demand by the industry and consumers was largely unmet e.g. delays in grant of project approvals and dispute resolution. There was no better time to introduce Real Estate (Regulations and Development) Act as the Indian Government is focusing on – housing for all, smart cities and infrastructure development, fulfilment of these goals will require enablers such as the Act.</p>
                    <p>The Act paves way for empowering all stakeholders engaged in the business and consumption of real estate, be it – consumers, real estate developers, brokers/ intermediaries amongst others. However all commercial and residential real estate including plots, apartments, shops, offices and other such properties are all covered under the Act.</p>
                    <p>A few of the overarching themes in the Act are following –</p>
                    <ol>
                        <li>Consumer rights and protection</li>
                        <li>Regulatory oversight on real estate developers and brokers/ intermediaries</li>
                        <li>Defining the duties of real estate developers and default scenarios</li>
                        <li>Setting up timelines for registration of projects and dispute resolution</li>
                        <li>Clearly defining penalties and liabilities of real estate developer and brokers/ intermediaries</li>
                        <li>Roles and duties of investors</li>
                    </ol>
                    <p>&nbsp;</p>
                    <p><strong>Definitions of often used terms in this document –</strong></p>
                    <p><strong>Consumer:</strong>&nbsp;A person who has bought/ booked / intends to buy a plot, apartment or building from a real estate developer.<br><strong>Real estate developer:</strong>&nbsp;A person who develops a building or a township of apartments and commercial complexes on an independently or a jointly owned land, which are later partially or completely sold to the consumers. It also includes a person who converts an existing building or apartments thereof and who acts as a builder, contractor or coloniser.<br><strong>Project:</strong>&nbsp;Is a real estate project that is undertaken by real estate developer and a project can be an offering of Units (defined below) of one kind of mixed (i.e. apartments, plots, offices, shop, building)</p>
                    <p><strong>Intermediary:</strong>&nbsp;An intermediary is a person who negotiates the transactions of buying and selling a property between two parties and receives remuneration for the same (It typically includes brokers and property dealers).<br><strong>Unit:</strong>&nbsp;A single apartment, plot, shop or an office which is a part of a building or township being developed<br><strong>Person:</strong>&nbsp;includes i) an individual; ii) a Hindu undivided family; iii) a company; iv) a firm under Indian Partnership Act; 1932 or Limited Liability Partnership Act, 2008, as the case may be; v) the Maharashtra Real State Regulatory Authority; vi) an association of persons or a body of individuals whether incorporated or not; vii) a co-operative society registered under any law relating to co-operative societies; viii) any such other entity as the appropriate Government, may specify in this behalf.</p>
                    <p><strong>Carpet Area:</strong>&nbsp;means the net usable floor area of an apartment, excluding the area covered by the external walls, areas under services shafts, exclusive balcony or verandah area and exclusive open terrace area, but includes the area covered by the internal partition walls of the apartment.</p>
                    <p><strong>&nbsp;</strong></p>
                    <p><strong>FAQs</strong></p>
                    <p><strong>Q1. What is Real Estate (Regulation and Development) Act, 2016?</strong></p>
                    <p>The Real Estate (Regulation and Development) Act, 2016 (the Act, from hereon) is a Government of India initiative to br/ing about the much needed transparency and order to the real estate related transactions by creating a systematic and a uniform regulatory environment, thereby protecting consumer interest and making real estate developers accountable for timely completion of projects. The Act paves the way for setting up of Real Estate Regulatory Authority (RERA, henceforth) for regulation and promotion of real estate sector while promoting transparency and equity in real estate transactions.</p>
                    <p><strong>Q2.&nbsp;</strong><strong>What was the need for setting up RERAs?</strong></p>
                    <p>Real estate sector is supposedly one of the largest contributor to Indian economy and amongst the largest employers too. However real estate transactions in the country have largely been a tiresome and ambiguous affair for consumers. Real estate developers have been found to violate prudential norms of conducting business which has further resulted in litigations and disputes. In worst cases consumers have been handed over poor quality units which at times can also be a hazard. The need for clean-up of this system was being felt for long.</p>
                    <ol>
                        <li>Primarily RERAs will have an oversight on the real estate transactions and promote timely and satisfactory completion of projects, protect consumer interest and br/ing about transparency in all proceedings related to the sale, construction and handover of projects.</li>
                        <li>The Act br/ings all stakeholders – consumer, real estate developer and intermediaries under the purview of the RERA.</li>
                        <li>RERA will also maintain a web portal which will host almost all the relevant information a consumer requires from a real estate developer including – details of land titles, project approvals, construction progress, names of intermediaries, contractors etc.</li>
                        <li>RERA thereby becomes one body which can be approached during disputes arising out of real estate transactions and contracts, and this body will have power to impose penalties and punishment as set out under the Act</li>
                    </ol>
                    <p><strong>Q3. Is the Act applicable to both residential and commercial projects?</strong></p>
                    <p>Yes.</p>
                    <p><strong>Q4. Are there any supporting government bodies set up to assist the RERA?</strong></p>
                    <p>Yes. A Central Advisory council will be set up to advise the Central Government on the implications of the Act, recommend policy, protect consumer interest and to oversee the growth and development of the real estate sector. In addition, there will be a dedicated Appellate Tribunal set up for RERAs to hear appeals from orders of the RERAs and the adjudicating officer.</p>
                    <p>&nbsp;</p>
                    <p>&nbsp;</p>
                    <p><strong>Real estate developer section</strong></p>
                    <p><strong>Q1. What are the roles and responsibilities of a real estate developer as stated in the Act?</strong></p>
                    <p>The RERA has made the following compulsory for them-</p>
                    <ol>
                        <li>It is mandatory for the real estate developer to register the project with the concerned RERA and obtain a valid registration number before going ahead with the project</li>
                        <li>The real estate developer is required to submit all documents related to the project which are considered necessary by the RERA</li>
                        <li>The real estate developer must deposit 70% of the amount received from the consumers in an escrow account from time to time and ensure that the amount is solely used for the project for which it was taken</li>
                        <li>Adhere to the project plan at all times</li>
                        <li>Refund the money taken from the consumers with applicable interest in case the project cannot be completed for some reason</li>
                        <li>Compensate the consumer for the time delay if any repair structural defects if any in the construction even after 5 years of handover of the project. The Act lists down roles and responsibilities of the real estate developer at project launch, construction and handover stages. In fact the Act goes a step further and makes the real estate developer accountable for the project quality up to 5 years after handover of the project. The Act has been drafted well to define various nuances of real estate sector such as – phase wise development, commencement certificate, occupancy certificate amongst others. Also in its spirit the Act puts an end to the practice of launches without approvals (sometimes referred as soft launch) thereby a consumer is guarded to that extent as a violating real estate developer will suffer revocation of registration, penalties and be listed on public portal as a defaulter.</li>
                    </ol>
                    <p><strong>Q2. What are the documents to be produced by the real estate developer during registration of a project with the RERA?</strong></p>
                    <p>Details of the project such as name, address, type, names and photographs of the Promoters etc.</p>
                    <ol>
                        <li>Details of project already launched by the real estate developer and their status (in the preceding 5 years)</li>
                        <li>Approval and commencement certificates obtained from the Maharashtra Real State Regulatory Authority for each phase of the project.</li>
                        <li>Sanctioned plan and layout plan, development plan for the project and details of facilities being made available like drinking water, electricity etc.</li>
                        <li>Proforma of allotment letter, agreement for sale and conveyance deed to be signed with the consumers</li>
                        <li>Number of garages and their respective areas which are for sale in project;</li>
                        <li>Location of the project with clear demarcation of the land dedicated for the project.</li>
                        <li>Number, type and carpet areas of units to be sold along with details of open areas if any like terraces, balconies etc.</li>
                        <li>Details of associated engineers, contractors and architects and intermediaries in the project</li>
                        <li>A declaration stating that the land of the project is verified authenticated and the developer has a legal title to it, that the project will be completed within specified timeline and that 70% of money received from the consumers shall be deposited in a dedicated escrow account and this amount will be used solely for that particular project.</li>
                    </ol>
                    <p><strong>Q3. The Act has mandated real estate developers to specify ‘carpet area’ rather than ‘super built up area’. How will that help?</strong></p>
                    <p>Carpet area is a measure of net usable area of the unit and does not include common areas, balconies, verandahs etc. whereas, the super built up area could be an addition of both. Therefore, to ensure that the consumer knows what he is paying for, it has been made mandatory for the real estate developer to specify carpet area. Essentially Carpet Area is the area within the walls of a unit where a consumer can reside or have his office. Even when the balconies, verandahs or terraces are exclusively available within a unit these cannot be added to the Carpet Area prescribed in the Act. The Act thereby enacts a straightforward definition to be adopted across the country.</p>
                    <p><strong>Q4. What are the actions to be taken by the RERA after an application has been submitted for project registration?</strong></p>
                    <p>The RERA is required to either grant registration or reject the application within 30 days of its submission. On acceptance of application, the real estate developer is to be provided with a login id and password to access the RERA portal for submission of documents and details. If the application is not in conformation with the guidelines and RERA finds it worth rejecting, it is mandatory that the applicant be heard in the matter before rejection.<br>This is a welcome change being br/ought through the Act that information pertaining to real estate projects will go online and regulators won’t even allow marketing of projects that are not registered with the RERA.</p>
                    <p><strong>Q5. What happens if the concerned RERA fails to respond to the applicant within the stipulated thirty days time?</strong></p>
                    <p>In this case, the application is considered accepted and the project, successfully registered. The RERA is mandated to provide the applicant a login id and password for its web portal within 7 days of expiry of the said period of thirty days.<br>The Act thereby sets timelines on the regulator within which it has to respond to various requests.</p>
                    <p><strong>&nbsp;</strong></p>
                    <p><strong>Q6. What is the validity period for a particular project registration?</strong></p>
                    <p>The registration will be valid for a period specified by the real estate developer in the application form. Hence the real estate developer is accountable to adhere to timelines otherwise he risks suffering losses/ penalties.</p>
                    <p><strong>Q7. Under what circumstances can the RERA extend the validity of the registration?</strong></p>
                    <p>The RERA, if it considers necessary, may extend the validity of registration in the event of a natural calamity like flood, drought, fire etc and also in case of a war. Basically only force majeure events are the ones where real estate developer can have some leeway of not delivering on time. However he is still required to make a presentation to RERA for seeking extension and pay applicable fee. Also such extension will be for a period of one year in aggregate.</p>
                    <p><strong>Q8.What happens to on-going projects? Will they have to be registered as well?</strong></p>
                    <p>Yes. If the project in question meets the criterion for registration (as defined ahead), the application for the same has to be submitted within 3 months of commencement of the Act.</p>
                    <p><strong>Q9. Do all projects fall under the radar of RERA? Are there any exceptions?</strong></p>
                    <p>No. Only projects which are still under construction at the time of enactment of the Act and any new project thereon are under the purview of the RERA, provided- they are developed on a land area of more than 500 sq meter or which have more than 8 units with all phases combined.</p>
                    <p>Essentially almost all large projects which have not obtained completion certificate will immediately come under the purview of the Act. Thereby consumers of under construction project can seek protection under the Act. While the central government provides for these minimum area requirements the local governments can change the area requirements to conform to the Act, if required such minimum area threshold can be revised even lower.</p>
                    <p><strong>Q10. Is there a common platform to access the details of the registered real estate developers and their projects?</strong></p>
                    <p>Yes. A web based system will be made operational within one year of establishment of the RERA, for submission of details and documents by the real estate developer and this information can easily be accessed by consumers.<br>It is for the first time that an initiative of this sort is coming into play whereby real estate developers have to make several declarations and comply with norms, while all such information is online for consumers to access.</p>
                    <p><strong>Q11. On what grounds can the RERA revoke a registration?</strong></p>
                    <p>Upon receiving a complaint against the real estate developer, the RERA can revoke registration if it is satisfied that the real estate developer has not complied to the rules and regulations stated under the Act or rules and regulations made thereunder, or has violated the terms and conditions of approval given by the Maharashtra Real State Regulatory Authority or is involved in unfair practices to sell, market or advertise his project.</p>
                    <p><strong>Q12. What are the prerequisites for a real estate developer to appeal to the Appellate Tribunal?</strong></p>
                    <p>The appeal made by the real estate developer will not be entertained by the Appellate Tribunal until he deposits 30% or higher of the penalty which would be decided in case of no appeal or the total amount to be paid to the consumer (which includes interest as well as the compensation to be paid) with the Appellate Tribunal.</p>
                    <p><strong>Q13. Does the RERA recognise agreement for sale or does it make it mandatory to register property at purchase to qualify?</strong></p>
                    <p>No, RERA recognises both registration of property and registration of agreement for sale. In fact the Act mandates that an agreement for sale needs to be registered once 10% of the contracted amount is collected from a consumer by real estate developer. This provision thereby takes into account that there is lack of uniformity across various states of India i.e. in some places property registration takes place at time of purchase while in others only an agreement for sale is signed at time of purchase.</p>
                    <p><strong>Q14. Can a real estate developer change plans once the project is launched or is under construction?</strong></p>
                    <p>The Act takes into account 2 scenarios –</p>
                    <ol>
                        <li>Minor changes – Minor changes can be made to a unit plan (which includes plans, fixtures, fittings etc) after proper declaration and intimation to the customer and certification by an architect or an engineer that such changes are required for architectural and structural reasons. Such minor changes are also allowed which are requested by a consumer. But these do not include changes in area or height, or removal of part of a building or any such change which the Maharashtra Real State Regulatory Authority feels materially deviates from the product offering.</li>
                        <li>Any other change i.e. change to sanctioned plans, layout plans, and specifications of buildings or common areas cannot be br/ought about without consent of at least 2/3rd of consumers of the project. The consenting consumers do not include real estate developer who might still own units in the project. In fact for the purposes of this clause the Act counts all such consumers who might own several units in a project through direct and indirect ownership (company, HUF and family) as one irrespective of the number of units held.</li>
                    </ol>
                    <p><strong>Q15. What is a project phase? Does a real estate developer need to register the complete project even if he is launching a project on just a small portion of it?</strong></p>
                    <p>The Act recognises that a large land parcel or a township isn’t developed at one go. In fact real estate developers may want to change plans of the subsequent projects launched in the township. Thereby the Act permits the real estate developers to register their projects in a phase wise manner as separate projects. Hence a real estate developer is then allowed to make changes in future to the phases not registered yet.</p>
                    <p><strong>Q16. What are the penalties that a real estate developer would face if he fails to adhere to the registration mandates or any other directions prescribed by the RERA?</strong></p>
                    <p>If the real estate developer violates the registration procedures prescribed by the Act, he will be required to pay up to 10% of the total estimated cost of the project in question. If found continuing the offence, the real estate developer will be punishable either with imprisonment (up to 3 years) or a fine which may extend up to a further 10% of the above project cost.</p>
                    <p><strong>Q17. How does the Act impact Joint Developer or Joint Venture Agreements where landlord and developer are two different parties but both are beneficiaries&nbsp;of sale of project?</strong></p>
                    <p>The Act makes both the developers and the landlord or any such party which is beneficiary of a sale of a project and receive payments from consumers as real estate developers (Promoters), and are liable to adhere to the Act.</p>
                    <p><strong>Q18. How does it impact the real estate developer’s arrangements with real estate agents, contractors, architect, structural engineers and similar parties(Declaration required at registration)</strong></p>
                    <p>Firstly only registered real estate agents are supposed to function in the real estate business. Also the Act makes it mandatory on the real estate developer to make a declaration about the real estate agents, architects, structural engineers and similar parties to the RERA. And since this information is all available online a consumer can have access to it at all the time.</p>
                    <p><strong>Q19.&nbsp;Are there norms on advertisements or promotions?</strong></p>
                    <p>This is one big change coming through as a result of imposition of stricter guidelines for marketing and timing of marketing of projects. It has been seen that real estate developers use attractive marketing material including br/ochures, media advertisements and other forms to lure consumers. However several times there is a big disconnect between actual product and what is being shown in the marketing collateral. The Act doesn’t permit such activities as anything shown in the marketing material needs to be in line with the final product or else real estate developer will be liable to penalties under the Act.</p>
                    <p>The advertisement or prospectus issued or published by the developer shall mention prominently the website address of the the Maharashtra Real State Regulatory Authority, wherein all details of the registered project have been entered and include the registration number obtained from the Authority and such other matters incidental thereto.</p>
                    <p><strong>Q20.&nbsp;Does a real estate developer need to report sales, progress and other such things with regards to projects?</strong></p>
                    <p>Yes, from the date of enactment of the Act the real estate developers will have to share information with the consumers on an on-going basis. This information includes – amount of sales concluded, progress of projects, receipt of pending approvals and other such declarations which are key to project delivery.</p>
                    <p><strong>Q21.&nbsp;Can a real estate developer exit the project mid-way by selling to another developer or party?</strong></p>
                    <p>While a developer is allowed to sell the project to another investor he can do so only by taking written approval of 2/3rd of project’s consumers and also the prior approval of the RERA. Again if a consumer or his family or by other means holds more than one unit in a project he is considered as one consumer only. Also the RERA need to be informed of such sale and incoming party then assumes all the rights and liabilities as the previous promoter of the project (including project delivery timelines and other such matters).</p>
                    <p>&nbsp;</p>
                    <p><strong>Intermediary section</strong></p>
                    <p><strong>Q1. What are the mandatory rules for an intermediary?</strong></p>
                    <p>An intermediary is required to be registered with the RERA and possess a valid registration number before facilitating a sale or purchase of a project or acting on behalf of any real estate developer for the same. He is also required to maintain and preserve books of account, records and documents as prescribed by the Act. He shall also facilitate the possession of all information to the consumer, at the time of booking and provide any other assistance as prescribed.</p>
                    <p><strong>Q2. On what grounds can the registration of an intermediary be revoked by the RERA?</strong></p>
                    <p>Misrepresentation, fraud, br/each of any terms and conditions of the Act and any sort of unfair practice can cause the registration to be revoked; but not before the intermediary is given a chance to be heard.</p>
                    <p>The Act makes it tougher for the intermediaries to conduct business in an unprofessional manner and in a way prompts them to adopt ethical means of dealing with consumers.</p>
                    <p><strong>Q3. What are the penalties that an intermediary would face if he fails to adhere to the mandates prescribed by the RERA?</strong></p>
                    <p>If an intermediary violates the rules prescribed by the RERA, he will be liable to a penalty for every day of the violation caused and the sum could increase up to 5% of the total estimated cost of the unit in question. If the intermediary br/eaches any orders, decisions or directions given by the Appellate Tribunal, he could face imprisonment of upto 1 year or would have to pay fine for each day of violation which may extend upto 10% of total estimated cost of the unit in question</p>
                    <p>&nbsp;</p>
                    <p><strong>Consumer section</strong></p>
                    <p><strong>Q1. What are the novel measures taken to secure consumer interest and empower him?</strong></p>
                    <ol>
                        <li>The consumer is entitled to receive information about the sanctioned plan, layout plan as approved by the the Maharashtra Real State Regulatory Authority, stage wise time schedule of the project completion and the services promised by the real estate developer like drinking water facility, electricity, sanitation etc. After receiving the physical possession of the unit, the consumer has a right to obtain the necessary documents and plans including that of the common areas.</li>
                        <li>The consumers can claim possession of the unit and the association of consumers can collectively claim possession of the common areas as declared by the real estate developer.</li>
                        <li>If the real estate developer fails to meet the timeline or does not deliver what was promised, the consumer has a right to claim refund of amount paid along with prescribed interest and compensation for the same</li>
                    </ol>
                    <p>Also consumers will have to be updated about project progress, sales and construction status by the real estate developer.</p>
                    <p><strong>Q2. What are the responsibilities of a consumer?</strong></p>
                    <ol>
                        <li>It is mandatory for a consumer to make timely payments to the real estate developer as per the agreement for sale. He will also have to pay his share of registration charges, municipal taxes, maintenance charges, ground rent, electricity charges, water supply charges and any other services.</li>
                        <li>Once the occupancy certificate is issued by the real estate developer, the consumer is required to take possession within two months’ time.</li>
                        <li>If the consumer is not able to make timely payments for his purchase, he is required to pay interest at a prescribed rate.</li>
                        <li>It is compulsory for a consumer to exhibit active participation in the formation of an association, a cooperative society or any federation of consumers.</li>
                        <li>A consumer shall participate towards registration of the conveyance deed of the unit.</li>
                    </ol>
                    <p><strong>Q3. What is an escrow account and why is RERA mandating 70% funds collected be deposited in an escrow account by a real estate developer?</strong></p>
                    <p>An escrow account is under the purview of a third party essentially a bank or a recognised lender. This provision thereby results in further oversight of the bank account and signing authority is with the escrow account manager say a trustee or a bank or a lender.</p>
                    <p>One of the biggest pain points for consumers has been project delays. Amongst other reasons for delay, the use of collections from one project into business expansion or construction of other project or siphoning of funds by real estate developers have also been primary causes. Thereby to protect consumer of a project the Act mandates that of all collections 70% funds be deposited in an escrow account maintained with a scheduled commercial bank. These funds can be accessed by a real estate developer solely for purpose of construction of the project to which it belongs. The real estate developer can withdraw funds from this account in proportion to stage of work. The request for withdrawal of funds is to be certified by an engineer, architect and a chartered accountant in practice that real estate developer’s claims are justified.</p>
                    <p>Thereby this de-risks consumer to an extent that his payments to real estate developer are being channelized for the good of the project where he owns a unit/ units.</p>
                    <p><strong>Q4.What is the provision for an aggrieved person to lodge a complaint? Does he have to go through the existing judicial system?</strong></p>
                    <p>The Act mandates setting up of an Appellate tribunal by the appropriate government within one year of the Act coming into force. So RERA is the first body to approach in case of disputes and as per set of rules this body can establish the nature of violation and prescribe the penalty/ punishment. Any person aggrieved by the decisions of the RERA or an adjudicating officer can appeal to the Appellate Tribunal. This set up will fast track the process of dispute settlement since it minimises the involvement of the existing judicial system.</p>
                    <p>A person can appeal in High Court if he is aggrieved by decision of the Appellate Tribunal however this isn’t allowed in cases where the decision was reached after consent of the disputing parties. The person has to approach High Court within 60 days of receiving the decision.</p>
                    <p><strong>Q5. What happens if an Appellate Tribunal is not established for a particular jurisdiction during the time of appeal?</strong></p>
                    <p>In this case, the appropriate Government shall appoint any other body as Appellate Tribunal that currently exists to hear the appeals in the interim.</p>
                    <p><strong>Q6. In the above case, what will happen if the Appellate Tribunal is established during the course of hearing?</strong></p>
                    <p>The particular appeal will be transferred to the established Appellate Tribunal under the Act and will no longer be with the one which is temporarily appointed.</p>
                    <p><strong>Q7. What actions are taken by the RERA after the registration of any real estate developer is revoked? How will the project be completed then?</strong></p>
                    <p>In the above case,</p>
                    <ol>
                        <li>The RERA will debar the real estate developer from accessing the web portal for the project in which he has defaulted and list him under the defaulters</li>
                        <li>The RERA will also inform RERAs of other states and union territories</li>
                        <li>It will direct the bank to freeze the bank account for the particular project and consequently unfreeze it to facilitate further development of project</li>
                        <li>Can consult the appropriate Government to employ the Maharashtra Real State Regulatory Authority to finish the project. The association of consumers have the first right to refuse any further developmental activities of the project</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
</section>